---
FSs:
  - fs_name: "/test_fs1"
    fs_type: jfs2
    vg_name: rootvg
    fs_state: present
    fs_size: 128M
    fs_auto_mount: true

  - fs_name: "/test_fs2"
    fs_type: jfs2
    vg_name: rootvg
    fs_state: present
    fs_size: 128M
    fs_auto_mount: true
